# Use root/root credentials

services:
  apache:
    build: ./apache2_image
    image: php:8.2-apache
    volumes:
      - ./public:/var/www/html
      - ./apache2_conf:/etc/apache2
    ports:
      - "80:80"
    depends_on:
      - db
      - composer
      - node

  node:
    image: node
    working_dir: /app
    volumes:
      - ./public:/app
    command: npm install

  composer:
    image: composer
    volumes:
      - ./public:/app
    command: composer install

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: askZ4hI40J99uOw2&*vEfI6b
      MYSQL_DATABASE: brand
      MYSQL_USER: brand
      MYSQL_PASSWORD: RpipYboYanEY
    volumes:
      - ./database:/var/lib/mysql